name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@886d35d74d4c866e5c71d6ac3806945a109cd2ba#egg=discrete-optimization
      - nbgitpuller
